# Generated by Django 4.2.19 on 2025-05-08 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AFRIMART', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.FileField(upload_to='shop_owner_photos')),
                ('Id_card', models.FileField(upload_to='shop_owner_IDs')),
                ('Shop_proof', models.FileField(upload_to='shop_owner_proofs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myshops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
