# Generated by Django 4.2.21 on 2025-06-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFRIMART', '0003_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='Additional_phone',
            field=models.IntegerField(default=677777777),
        ),
        migrations.AddField(
            model_name='vendor',
            name='Fullname',
            field=models.CharField(default='fullname', max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='Market_location',
            field=models.CharField(default='location', max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='Profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='vendor',
            name='Shop_description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='Shop_name',
            field=models.CharField(default='shopname', max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='Stall_number',
            field=models.CharField(blank=True, default='stall', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='Whatsapp_no',
            field=models.IntegerField(default=677777777),
        ),
    ]
