# Generated by Django 4.2.21 on 2025-06-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFRIMART', '0004_vendor_additional_phone_vendor_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='Profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='VendorImage'),
        ),
    ]
